#!/usr/bin/env bash

# clean build directory
rm -rf dist

# bundled JS
webpack
NODE_ENV=production webpack

# CSS
stylus -o dist/liqvid.css styl/liqvid.styl
stylus -c -o dist/liqvid.min.css styl/liqvid.styl
