packages:
  # all packages in subdirs of packages/
  - "packages/**"

catalog:
  "@lqv/playback": "^0.2.2"

  # devDependencies
  "@biomejs/biome": 2.3.8

catalogs:
  peer:
    "@types/react": ">=18"
    "@types/react-dom": ">=18"
    react: ">=18"
    react-dom: ">=18"
