import * as stylex from "@stylexjs/stylex";

import {
  colors,
  dims,
  radii,
  spacing,
  text,
  typeface,
} from "#_/design/tokens.stylex.js";

export const shareStyles = stylex.create({
  addButton: {
    alignItems: "center",
    backgroundColor: {
      ":disabled": colors.graySubtle,
      ":hover": colors.grayHover,
      default: colors.graySubtle,
    },
    borderColor: colors.graySep,
    borderRadius: radii.md,
    borderStyle: "solid",
    borderWidth: dims.sep,
    color: {
      ":disabled": colors.grayDim,
      default: colors.grayNormal,
    },
    cursor: {
      ":disabled": "default",
      default: "pointer",
    },
    display: "flex",
    fontSize: text.rem075,
    gap: spacing.xs,
    paddingBlock: spacing.rem0375,
    paddingInline: spacing.rem0625,
    transition: "background-color 0.15s",
  },
  closeButton: {
    backgroundColor: colors.transparent,
    borderStyle: "none",
    color: {
      ":hover": colors.grayNormal,
      default: colors.grayDim,
    },
    cursor: "pointer",
    padding: spacing.rem025,
  },
  confirmMessage: {
    color: colors.grayDim,
    fontSize: text.rem0875,
    lineHeight: 1.5,
    marginBlock: spacing.rem1,
    marginInline: spacing.zero,
  },
  copyButton: {
    alignItems: "center",
    backgroundColor: {
      ":hover": colors.copyBtnBgHover,
      default: colors.copyBtnBg,
    },
    borderColor: colors.copyBtnBorder,
    borderRadius: radii.md,
    borderStyle: "solid",
    borderWidth: dims.sep,
    color: colors.copyBtnColor,
    cursor: "pointer",
    display: "flex",
    fontSize: text.rem0625,
    fontWeight: 500,
    gap: spacing.xs,
    paddingBlock: spacing.rem0375,
    paddingInline: spacing.rem05,
    transition: "background-color 0.15s",
  },
  deleteButton: {
    alignItems: "center",
    backgroundColor: {
      ":hover": colors.deleteBtnBgHover,
      default: colors.errorSubtle,
    },
    borderColor: colors.deleteBtnBorder,
    borderRadius: radii.md,
    borderStyle: "solid",
    borderWidth: dims.sep,
    color: colors.errorText,
    cursor: "pointer",
    display: "flex",
    justifyContent: "center",
    padding: spacing.sm,
    transition: "background-color 0.15s",
  },
  deleteConfirmButton: {
    alignItems: "center",
    backgroundColor: {
      ":hover": colors.errorSolidHover,
      default: colors.errorSolid,
    },
    borderRadius: radii.md,
    borderStyle: "none",
    color: colors.white,
    columnGap: "0.2em",
    cursor: "pointer",
    display: "flex",
    fontSize: text.rem0875,
    fontWeight: 500,
    paddingBlock: spacing.rem05,
    paddingInline: spacing.rem1,
    rowGap: "0.2em",
    transition: "background-color 0.15s",
  },
  emptyMessage: {
    color: colors.grayDim,
    fontSize: text.rem0875,
    padding: spacing.xl,
    textAlign: "center",
  },
  loading: {
    alignItems: "center",
    display: "flex",
    justifyContent: "center",
    padding: spacing.rem2,
  },
  presetButton: {
    backgroundColor: {
      ":hover": colors.grayHover,
      default: colors.graySubtle,
    },
    borderColor: colors.graySep,
    borderRadius: radii.md,
    borderStyle: "solid",
    borderWidth: dims.sep,
    color: colors.grayNormal,
    cursor: "pointer",
    fontSize: text.rem075,
    paddingBlock: spacing.rem0375,
    paddingInline: spacing.rem075,
    transition: "background-color 0.15s, border-color 0.15s",
  },
  presetButtonActive: {
    backgroundColor: colors.accentSolid,
    borderColor: colors.accentSolid,
    color: colors.white,
  },
  productionLink: {
    color: {
      ":hover": colors.grayNormal,
      default: colors.grayDim,
    },
    marginLeft: "auto",
    textAlign: "right",
    textDecoration: "none",
    width: "min-content",
  },
  renderActionButton: {
    alignItems: "center",
    backgroundColor: {
      ":hover": colors.grayHover,
      default: colors.graySubtle,
    },
    borderColor: colors.graySep,
    borderRadius: radii.md,
    borderStyle: "solid",
    borderWidth: dims.sep,
    color: colors.grayNormal,
    cursor: "pointer",
    display: "flex",
    justifyContent: "center",
    padding: spacing.sm,
    transition: "background-color 0.15s",
  },
  renderActions: {
    display: "flex",
    flexShrink: 0,
    gap: spacing.sm,
  },
  renderDate: {
    color: colors.grayNormal,
    fontSize: text.rem08125,
    fontWeight: 500,
  },
  renderDetails: {
    color: colors.grayDim,
    display: "flex",
    fontSize: text.rem06875,
    gap: spacing.lg,
  },
  renderHeader: {
    alignItems: "center",
    display: "flex",
    gap: spacing.lg,
  },
  renderInfo: {
    display: "flex",
    flex: "1",
    flexDirection: "column",
    gap: spacing.xs,
    minWidth: 0,
  },
  renderItem: {
    alignItems: "center",
    backgroundColor: colors.grayApp,
    borderColor: colors.graySep,
    borderRadius: radii.lg,
    borderStyle: "solid",
    borderWidth: dims.sep,
    display: "flex",
    gap: spacing.lg,
    justifyContent: "space-between",
    padding: spacing.lg,
  },
  renderList: {
    display: "flex",
    flexDirection: "column",
    gap: spacing.md,
    listStyle: "none",
    margin: spacing.zero,
    maxHeight: "300px",
    overflowY: "auto",
    padding: spacing.zero,
  },
  renderName: {
    color: colors.grayNormal,
    fontSize: text.rem08125,
    fontWeight: 500,
  },
  renderStatus: {
    alignItems: "center",
    color: colors.grayDim,
    display: "flex",
    fontSize: text.rem075,
    gap: spacing.xs,
  },
  resolutionPresets: {
    display: "flex",
    gap: spacing.md,
    marginBottom: spacing.md,
  },
  section: {
    marginTop: spacing.xl,
  },
  sectionActions: {
    alignItems: "center",
    display: "flex",
    gap: spacing.md,
    justifyContent: "flex-end",
    marginBottom: spacing.lg,
  },
  sectionHeader: {
    alignItems: "center",
    display: "flex",
    gap: spacing.md,
    justifyContent: "space-between",
    marginBottom: spacing.lg,
  },
  seekSlider: {
    appearance: "none",
    backgroundColor: colors.graySep,
    borderRadius: radii.md,
    flex: "1",
    height: "6px",
  },
  shareDialog: {
    maxWidth: "36rem",
  },
  shareTabs: {
    marginTop: spacing.xl,
  },
  statusCompleted: {
    color: colors.successSolid,
  },
  statusFailed: {
    color: colors.errorSolid,
  },
  textInput: {
    backgroundColor: colors.grayApp,
    borderColor: {
      ":focus": colors.accentSolid,
      default: colors.graySep,
    },
    borderRadius: radii.md,
    borderStyle: "solid",
    borderWidth: dims.sep,
    color: colors.grayNormal,
    fontSize: text.rem0875,
    outline: {
      ":focus": "none",
      default: null,
    },
    paddingBlock: spacing.rem05,
    paddingInline: spacing.rem075,
    width: "100%",
  },
  thumbsPreview: {
    display: "flex",
    flexDirection: "column",
    gap: spacing.xl,
  },
  thumbsPreviewBox: {
    backgroundColor: colors.graySubtle,
    borderColor: colors.graySep,
    borderRadius: radii.lg,
    borderStyle: "solid",
    borderWidth: dims.sep,
    overflow: "hidden",
    position: "relative",
  },
  thumbsPreviewBoxImg: {
    position: "absolute",
  },
  thumbsPreviewItem: {
    alignItems: "center",
    display: "flex",
    flexDirection: "column",
    gap: spacing.md,
  },
  thumbsPreviewRow: {
    display: "flex",
    gap: spacing.lg,
    justifyContent: "center",
  },
  thumbsSchemeLabel: {
    color: colors.grayDim,
    fontSize: text.rem075,
    fontWeight: 500,
    textTransform: "uppercase",
  },
  thumbsSliderControls: {
    alignItems: "center",
    display: "flex",
    gap: spacing.lg,
    paddingBlock: spacing.zero,
    paddingInline: spacing.rem025,
  },
  timeDisplay: {
    color: colors.grayDim,
    fontFamily: typeface.mono,
    fontSize: text.rem075,
    minWidth: "3rem",
    textAlign: "center",
    userSelect: "none",
  },
});
