import * as stylex from "@stylexjs/stylex";

import { colors, radii, spacing } from "#_/design/tokens.stylex.js";

const spin = stylex.keyframes({
  from: { transform: "rotate(0deg)" },
  to: { transform: "rotate(360deg)" },
});

export const shareStyles = stylex.create({
  addButton: {
    alignItems: "center",
    backgroundColor: {
      ":disabled": colors.graySubtle,
      ":hover": colors.grayHover,
      default: colors.graySubtle,
    },
    borderColor: colors.graySep,
    borderRadius: radii.md,
    borderStyle: "solid",
    borderWidth: "1px",
    color: {
      ":disabled": colors.grayDim,
      default: colors.grayNormal,
    },
    cursor: {
      ":disabled": "default",
      default: "pointer",
    },
    display: "flex",
    fontSize: "0.75rem",
    gap: spacing.xs,
    paddingBlock: "0.375rem",
    paddingInline: "0.625rem",
    transition: "background-color 0.15s",
  },
  closeButton: {
    backgroundColor: "transparent",
    borderStyle: "none",
    color: {
      ":hover": colors.grayNormal,
      default: colors.grayDim,
    },
    cursor: "pointer",
    padding: "0.25rem",
  },
  confirmMessage: {
    color: colors.grayDim,
    fontSize: "0.875rem",
    lineHeight: 1.5,
    marginBlock: "1rem",
    marginInline: "0",
  },
  copyButton: {
    alignItems: "center",
    backgroundColor: {
      ":hover": "light-dark(#d0e8ff, #2a4a7f)",
      default: "light-dark(#e8f4ff, #1e3a5f)",
    },
    borderColor: "light-dark(#b3d4ff, #2a5a8f)",
    borderRadius: radii.md,
    borderStyle: "solid",
    borderWidth: "1px",
    color: "light-dark(#0066cc, #66b3ff)",
    cursor: "pointer",
    display: "flex",
    fontSize: "0.625rem",
    fontWeight: 500,
    gap: spacing.xs,
    paddingBlock: "0.375rem",
    paddingInline: "0.5rem",
    transition: "background-color 0.15s",
  },
  deleteButton: {
    alignItems: "center",
    backgroundColor: {
      ":hover": "light-dark(#f9d7d3, #4a2424)",
      default: colors.errorSubtle,
    },
    borderColor: "light-dark(#f5c6c2, #5a2a2a)",
    borderRadius: radii.md,
    borderStyle: "solid",
    borderWidth: "1px",
    color: colors.errorText,
    cursor: "pointer",
    display: "flex",
    justifyContent: "center",
    padding: spacing.sm,
    transition: "background-color 0.15s",
  },
  deleteConfirmButton: {
    alignItems: "center",
    backgroundColor: {
      ":hover": colors.errorSolidHover,
      default: colors.errorSolid,
    },
    borderRadius: radii.md,
    borderStyle: "none",
    color: "#fff",
    cursor: "pointer",
    display: "flex",
    fontSize: "0.875rem",
    fontWeight: 500,
    gap: "0.2em",
    paddingBlock: "0.5rem",
    paddingInline: "1rem",
    transition: "background-color 0.15s",
  },
  emptyMessage: {
    color: colors.grayDim,
    fontSize: "0.875rem",
    padding: spacing.xl,
    textAlign: "center",
  },
  loading: {
    alignItems: "center",
    display: "flex",
    justifyContent: "center",
    padding: "2rem",
  },
  presetButton: {
    backgroundColor: {
      ":hover": colors.grayHover,
      default: colors.graySubtle,
    },
    borderColor: colors.graySep,
    borderRadius: radii.md,
    borderStyle: "solid",
    borderWidth: "1px",
    color: colors.grayNormal,
    cursor: "pointer",
    fontSize: "0.75rem",
    paddingBlock: "0.375rem",
    paddingInline: "0.75rem",
    transition: "background-color 0.15s, border-color 0.15s",
  },
  presetButtonActive: {
    backgroundColor: colors.accentSolid,
    borderColor: colors.accentSolid,
    color: "#fff",
  },
  productionLink: {
    color: {
      ":hover": colors.grayNormal,
      default: colors.grayDim,
    },
    marginLeft: "auto",
    textAlign: "right",
    textDecoration: "none",
    width: "min-content",
  },
  renderActionButton: {
    alignItems: "center",
    backgroundColor: {
      ":hover": colors.grayHover,
      default: colors.graySubtle,
    },
    borderColor: colors.graySep,
    borderRadius: radii.md,
    borderStyle: "solid",
    borderWidth: "1px",
    color: colors.grayNormal,
    cursor: "pointer",
    display: "flex",
    justifyContent: "center",
    padding: spacing.sm,
    transition: "background-color 0.15s",
  },
  renderActions: {
    display: "flex",
    flexShrink: 0,
    gap: spacing.sm,
  },
  renderDate: {
    color: colors.grayNormal,
    fontSize: "0.8125rem",
    fontWeight: 500,
  },
  renderDetails: {
    color: colors.grayDim,
    display: "flex",
    fontSize: "0.6875rem",
    gap: spacing.lg,
  },
  renderHeader: {
    alignItems: "center",
    display: "flex",
    gap: spacing.lg,
  },
  renderInfo: {
    display: "flex",
    flex: "1",
    flexDirection: "column",
    gap: spacing.xs,
    minWidth: 0,
  },
  renderItem: {
    alignItems: "center",
    backgroundColor: colors.grayApp,
    borderColor: colors.graySep,
    borderRadius: radii.lg,
    borderStyle: "solid",
    borderWidth: "1px",
    display: "flex",
    gap: spacing.lg,
    justifyContent: "space-between",
    padding: spacing.lg,
  },
  renderList: {
    display: "flex",
    flexDirection: "column",
    gap: spacing.md,
    listStyle: "none",
    margin: 0,
    maxHeight: "300px",
    overflowY: "auto",
    padding: 0,
  },
  renderName: {
    color: colors.grayNormal,
    fontSize: "0.8125rem",
    fontWeight: 500,
  },
  renderStatus: {
    alignItems: "center",
    color: colors.grayDim,
    display: "flex",
    fontSize: "0.75rem",
    gap: spacing.xs,
  },
  resolutionPresets: {
    display: "flex",
    gap: spacing.md,
    marginBottom: spacing.md,
  },
  section: {
    marginTop: spacing.xl,
  },
  sectionActions: {
    alignItems: "center",
    display: "flex",
    gap: spacing.md,
    justifyContent: "flex-end",
    marginBottom: spacing.lg,
  },
  sectionHeader: {
    alignItems: "center",
    display: "flex",
    gap: spacing.md,
    justifyContent: "space-between",
    marginBottom: spacing.lg,
  },
  seekSlider: {
    appearance: "none",
    backgroundColor: colors.graySep,
    borderRadius: radii.md,
    flex: "1",
    height: "6px",
  },
  shareDialog: {
    maxWidth: "36rem",
  },
  shareTabs: {
    marginTop: spacing.xl,
  },
  spinner: {
    animationDuration: "1s",
    animationIterationCount: "infinite",
    animationName: spin,
    animationTimingFunction: "linear",
  },
  statusCompleted: {
    color: colors.successSolid,
  },
  statusFailed: {
    color: colors.errorSolid,
  },
  textInput: {
    backgroundColor: colors.grayApp,
    borderColor: {
      ":focus": colors.accentSolid,
      default: colors.graySep,
    },
    borderRadius: radii.md,
    borderStyle: "solid",
    borderWidth: "1px",
    color: colors.grayNormal,
    fontSize: "0.875rem",
    outline: {
      ":focus": "none",
    },
    paddingBlock: "0.5rem",
    paddingInline: "0.75rem",
    width: "100%",
  },
  thumbsPreview: {
    display: "flex",
    flexDirection: "column",
    gap: spacing.xl,
  },
  thumbsPreviewBox: {
    backgroundColor: colors.graySubtle,
    borderColor: colors.graySep,
    borderRadius: radii.lg,
    borderStyle: "solid",
    borderWidth: "1px",
    overflow: "hidden",
    position: "relative",
  },
  thumbsPreviewBoxImg: {
    position: "absolute",
  },
  thumbsPreviewItem: {
    alignItems: "center",
    display: "flex",
    flexDirection: "column",
    gap: spacing.md,
  },
  thumbsPreviewRow: {
    display: "flex",
    gap: spacing.lg,
    justifyContent: "center",
  },
  thumbsSchemeLabel: {
    color: colors.grayDim,
    fontSize: "0.75rem",
    fontWeight: 500,
    textTransform: "uppercase",
  },
  thumbsSliderControls: {
    alignItems: "center",
    display: "flex",
    gap: spacing.lg,
    paddingBlock: "0",
    paddingInline: "0.25rem",
  },
  timeDisplay: {
    color: colors.grayDim,
    fontFamily: "monospace",
    fontSize: "0.75rem",
    minWidth: "3rem",
    textAlign: "center",
    userSelect: "none",
  },
});
